#!/bin/sh

export PORT="-Dserver.port=8080"
export SPRING_PROFILE="-Dspring.profiles.active=postgresql,ddl-create"
export DATABASE_URL="-Dspring.datasource.url=jdbc:postgresql://localhost:5432/cake"
export VERSION="1.1.0"

mvn clean install -P postgresql
java $PORT $JAVA_OPTS $SPRING_PROFILE $DATABASE_URL -jar target/gundulf.products-$VERSION.jar


